/* ===========================================================================
   MODAL LAB — data for the four mini-games and the flashcard deck.
   Plain ES5, loaded by a script tag. Text is plain text; only the `why`
   fields may carry em/strong tags.
     LAB.dial         Certainty Dial — 8 scenes (rungs: cant · weak · should · will · must);
                      optional `chip` overrides the scene button label
     LAB.detective    Modal Detective — 40 cases (20 now, 20 past; must / might / cant)
     LAB.cliff        The Negation Cliff — 40 sentences (free = no obligation, ban = not allowed)
     LAB.timeMachine  Time Machine — 30 items (pick the correct past version; key 10/10/10)
     MODAL_CARDS      Leitner flashcards: [form, function, CEFR, theme, meaning, Thai, example]
     MODAL_CARD_THEMES
   =========================================================================== */

var LAB = {

  /* ------------------------------------------------------------ DIAL */
  dial: [
    { id: 'dial1', subject: 'Ploy', now: 'be at the library', past: 'been at the library',
      thai: 'พลอยอยู่ที่ห้องสมุด',
      evidence: [
        { text: 'Her bag is on a library desk and her laptop is open next to it.', rung: 'must', time: 'now' },
        { text: 'She sometimes studies there after school, but not always.', rung: 'weak', time: 'now' },
        { text: 'The library has been closed all week for repairs.', rung: 'cant', time: 'now' },
        { text: 'She planned to leave at 7 for the library, a ten-minute walk away. It is now 7:30. If she left on time, she’s there.', rung: 'should', time: 'now' },
        { text: 'It’s Monday at 4:30, and Ploy has spent every Monday afternoon in the library since M1. No need to check.', rung: 'will', time: 'now' },
        { text: 'Yesterday her friend saw her going in with a pile of books.', rung: 'must', time: 'past' },
        { text: 'Yesterday she was on the school trip to Ayutthaya from 8 a.m. to 9 p.m., and the library closes at 6.', rung: 'cant', time: 'past' },
        { text: 'After tutoring last night she went either to the library or straight home. Her mum isn’t sure which.', rung: 'weak', time: 'past' }
      ] },

    { id: 'dial2', chip: 'The caller · Grandma', subject: 'That', now: 'be Grandma', past: 'been Grandma',
      thai: 'คนที่โทรมาคือคุณยาย',
      evidence: [
        { text: 'The phone is ringing at 8 p.m. on Sunday, and Grandma has called at exactly 8 every Sunday for years. You don’t even look at the screen.', rung: 'will', time: 'now' },
        { text: 'The screen shows Grandma’s home number, and she lives on her own.', rung: 'must', time: 'now' },
        { text: 'It’s a number you don’t recognise. Grandma has been talking about getting a new SIM card, but you don’t know if she has.', rung: 'weak', time: 'now' },
        { text: 'The phone is ringing, but Grandma is sitting right next to you on the sofa, watching a Thai drama.', rung: 'cant', time: 'now' },
        { text: 'It’s 8:20 and the phone is ringing. Grandma’s flight was due to land at 8 and she planned to call after landing, but you haven’t checked whether the flight was on time.', rung: 'should', time: 'now' },
        { text: 'There’s a missed call from Grandma’s home number, and nobody else uses that phone.', rung: 'must', time: 'past' },
        { text: 'The missed call came while Grandma was on a plane with her phone switched off.', rung: 'cant', time: 'past' },
        { text: 'The missed call was from a hidden number. Grandma sometimes hides her number, but so do people selling insurance.', rung: 'weak', time: 'past' }
      ] },

    { id: 'dial3', subject: 'Mint', now: 'know about the surprise party', past: 'known about the surprise party',
      thai: 'มิ้นท์รู้เรื่องปาร์ตี้เซอร์ไพรส์',
      evidence: [
        { text: 'Mint just sent the group chat a message: “Whatever you’re planning for Saturday, I’m wearing my blue dress.”', rung: 'must', time: 'now' },
        { text: 'Mint walked past while the group was talking about the party. Nobody is sure whether she heard anything.', rung: 'weak', time: 'now' },
        { text: 'The plan was made in a LINE group Mint isn’t in, and she has been at a camp with no phone all week.', rung: 'cant', time: 'now' },
        { text: 'When everyone jumped out and shouted “Surprise!”, Mint didn’t even blink. She just said, “Finally!”', rung: 'must', time: 'past' },
        { text: 'When the lights came on, Mint screamed, dropped her drink and burst into happy tears.', rung: 'cant', time: 'past' },
        { text: 'Mint looked a little surprised at the party, but she had also done her hair and make-up, which she rarely does.', rung: 'weak', time: 'past' }
      ] },

    { id: 'dial4', subject: 'The parcel', now: 'be downstairs in the mailroom', past: 'been delivered to the mailroom',
      thai: 'พัสดุอยู่ที่ห้องรับพัสดุชั้นล่าง',
      evidence: [
        { text: 'The tracking app said “Arriving before 2 p.m.”, and it is now 4 p.m.', rung: 'should', time: 'now' },
        { text: 'The security guard waved at you, pointed at the mailroom and called out, “Box for you!”', rung: 'must', time: 'now' },
        { text: 'The app hasn’t updated since this morning. Deliveries to your building sometimes come before lunch and sometimes the next day.', rung: 'weak', time: 'now' },
        { text: 'You picked the parcel up from the mailroom ten minutes ago, and it’s on your desk.', rung: 'cant', time: 'now' },
        { text: 'The mailroom logbook shows a box for your room signed in at 9:14 this morning, and you ordered only one thing.', rung: 'must', time: 'past' },
        { text: 'The shop has just emailed: your order was cancelled before it was ever sent.', rung: 'cant', time: 'past' },
        { text: 'The driver called while you were out. He either left it at the mailroom or took it back to the depot.', rung: 'weak', time: 'past' }
      ] },

    { id: 'dial5', subject: 'Fern', now: 'be asleep', past: 'been asleep',
      thai: 'เฟิร์นหลับอยู่',
      evidence: [
        { text: 'Her light is off, and you can hear her snoring through the door.', rung: 'must', time: 'now' },
        { text: 'It’s 10 p.m. She hasn’t answered your LINE for ten minutes, but she often forgets to check her phone.', rung: 'weak', time: 'now' },
        { text: 'You can hear her singing K-pop very loudly in the shower.', rung: 'cant', time: 'now' },
        { text: 'It’s 11 p.m. Since she started 5 a.m. swimming training, Fern has been asleep by 10:30 every night. No need to check.', rung: 'will', time: 'now' },
        { text: 'On last night’s group video call, Fern’s camera showed her with her eyes shut and her mouth open.', rung: 'must', time: 'past' },
        { text: 'At 2 a.m. last night Fern sent the class group her finished essay with the message “DONE!!!”', rung: 'cant', time: 'past' },
        { text: 'Fern didn’t answer when you called at 10 last night. She was either asleep or in the shower.', rung: 'weak', time: 'past' }
      ] },

    { id: 'dial6', subject: 'Our teacher', now: 'be stuck in traffic', past: 'been stuck in traffic',
      thai: 'คุณครูรถติดอยู่',
      evidence: [
        { text: 'She is ten minutes late. She drives to school, but she sometimes stops to buy coffee on the way.', rung: 'weak', time: 'now' },
        { text: 'She just phoned on hands-free: all you can hear is horns, and she says she hasn’t moved for ten minutes on Sukhumvit Road.', rung: 'must', time: 'now' },
        { text: 'She told us she would come by BTS today, because her car is at the garage.', rung: 'cant', time: 'now' },
        { text: 'She arrived forty minutes late this morning, red in the face, saying “Sukhumvit!” and drinking a whole bottle of water.', rung: 'must', time: 'past' },
        { text: 'She was late this morning, but she lives two minutes away and always walks to school.', rung: 'cant', time: 'past' },
        { text: 'She was fifteen minutes late yesterday and didn’t say why. She drives in, but she also had a dentist appointment that morning.', rung: 'weak', time: 'past' }
      ] },

    { id: 'dial7', subject: 'Nan', now: 'have a cold', past: 'had a cold',
      thai: 'แนนเป็นหวัด',
      evidence: [
        { text: 'She keeps sneezing, her nose is red, and there’s a huge pile of tissues on her desk.', rung: 'must', time: 'now' },
        { text: 'She’s wearing a face mask today, but she sometimes wears one just because of the PM2.5.', rung: 'weak', time: 'now' },
        { text: 'She had a full check-up this morning, and the school nurse says she is perfectly healthy.', rung: 'cant', time: 'now' },
        { text: 'Last week she was off school for three days, and her mum’s note said “cough and runny nose”.', rung: 'must', time: 'past' },
        { text: 'Her mum says Nan hasn’t been ill once this year, and she hasn’t missed a single day of school.', rung: 'cant', time: 'past' },
        { text: 'Her voice was croaky at the weekend, but she had also been cheering at a football match all afternoon.', rung: 'weak', time: 'past' }
      ] },

    { id: 'dial8', subject: 'The M4 bus', now: 'be in Kanchanaburi', past: 'reached Kanchanaburi',
      thai: 'รถบัสของ ม.4 อยู่ที่กาญจนบุรี',
      evidence: [
        { text: 'The bus was due to leave at 7, the journey takes about three hours, and it is now 10:30. If everything went to plan, they’re there.', rung: 'should', time: 'now' },
        { text: 'The class group chat is full of photos of Erawan Waterfall, all posted in the last five minutes.', rung: 'must', time: 'now' },
        { text: 'It’s 10:30. The bus left on time, but there was a crash on the highway and nobody is answering their phone.', rung: 'weak', time: 'now' },
        { text: 'It’s 7:15 a.m., and the bus only left school fifteen minutes ago.', rung: 'cant', time: 'now' },
        { text: 'At 11 a.m. yesterday, Bow posted a selfie at Erawan Waterfall with the caption “We made it!”', rung: 'must', time: 'past' },
        { text: 'Yesterday the bus broke down outside the school gate, and the trip was cancelled.', rung: 'cant', time: 'past' },
        { text: 'Bow’s 11 a.m. photo yesterday shows a waterfall, but it could be almost any waterfall in Kanchanaburi.', rung: 'weak', time: 'past' }
      ] }
  ],

  /* ------------------------------------------------------- DETECTIVE */
  detective: [
    /* ---- now ---- */
    { id: 'det1', time: 'now', clue: 'The lights are off, the curtains are closed and there are three newspapers on the doorstep.',
      sentence: 'The Wongs ___ be away.', answer: 'must',
      why: 'Three days of papers and a dark house leave one explanation, so <em>must</em> (≈90% sure).' },
    { id: 'det2', time: 'now', clue: 'Ploy has bought a birthday cake, twenty party hats and enough mookata for a small army.',
      sentence: 'She ___ be planning a party.', answer: 'must',
      why: 'Cake, hats and food for twenty point one way only: <em>must</em>.' },
    { id: 'det3', time: 'now', clue: 'Bam says she’s at the cinema, but she just sent a selfie from the school canteen with a plate of pad kra pao.',
      sentence: 'She ___ be at the cinema.', answer: 'cant',
      why: 'The selfie puts her in the canteen, which rules the cinema out: <em>can’t</em>.' },
    { id: 'det4', time: 'now', clue: 'The BTS is five minutes late. That sometimes just means a slow train ahead, and sometimes a breakdown at Siam.',
      sentence: 'There ___ be a problem on the line.', answer: 'might',
      why: 'A late train can mean a small delay or a real problem. The evidence points both ways: <em>might</em>.' },
    { id: 'det5', time: 'now', clue: 'Kaew has opened the fridge six times in ten minutes and keeps asking, “Is there anything to eat?”',
      sentence: 'She ___ be hungry.', answer: 'must',
      why: 'Six trips to the fridge leave little doubt: <em>must</em>.' },
    { id: 'det6', time: 'now', clue: 'Mild has just finished two plates of khao man gai, a mango sticky rice and a whole bag of crisps.',
      sentence: 'She ___ be hungry again already!', answer: 'cant',
      why: 'After all that food, hunger is ruled out: <em>can’t</em>. The opposite of <em>must</em> here is <em>can’t</em>, not <em>mustn’t</em>.' },
    { id: 'det7', time: 'now', clue: 'June has read your LINE message but hasn’t replied. She often replies hours later, but you did forget her birthday.',
      sentence: 'June ___ be annoyed with you.', answer: 'might',
      why: 'Late replies are normal for June, but the birthday is a reason too. Two explanations: <em>might</em>.' },
    { id: 'det8', time: 'now', clue: 'The 7-Eleven next to school has sold out of cold drinks and ice, and there’s a queue out of the door. It’s 38°C.',
      sentence: 'Everyone ___ be really thirsty today.', answer: 'must',
      why: 'No cold drinks left, a long queue and 38°C: <em>must</em>.' },
    { id: 'det9', time: 'now', clue: 'Pim says her Grab is outside, but the app shows the driver is still 12 kilometres away.',
      sentence: 'The car outside ___ be her Grab.', answer: 'cant',
      why: 'The app puts her driver 12 km away, so the car outside is ruled out: <em>can’t</em>.' },
    { id: 'det10', time: 'now', clue: 'A girl on the BTS is carrying the same English coursebook as you, but several schools in Bangkok use that book.',
      sentence: 'She ___ go to your school.', answer: 'might',
      why: 'The book fits your school, but it fits other schools too: <em>might</em>.' },
    { id: 'det11', time: 'now', clue: 'Your tutor is yawning, has three empty coffee cups on her desk and keeps calling you by the wrong name.',
      sentence: 'She ___ be exhausted.', answer: 'must',
      why: 'Yawns, three coffees and the wrong name: all the evidence points one way, so <em>must</em>.' },
    { id: 'det12', time: 'now', clue: 'The singer on the poster says he’s “only 25”, but your mum says he was already famous when she was at school.',
      sentence: 'He ___ be 25.', answer: 'cant',
      why: 'Famous when your mum was at school? Twenty-five is ruled out: <em>can’t</em>.' },
    { id: 'det13', time: 'now', clue: 'There’s a huge queue outside the new bubble-tea shop at Siam Square, but a sign says “Free drinks for the first 100 customers!”',
      sentence: 'The tea ___ be really good.', answer: 'might',
      why: 'The queue could be for great tea or just for free tea: <em>might</em>.' },
    { id: 'det14', time: 'now', clue: 'Fah has packed her bag, keeps checking the clock and is standing by the classroom door five minutes before the bell.',
      sentence: 'She ___ be in a hurry to leave.', answer: 'must',
      why: 'Bag packed, eyes on the clock, waiting at the door: <em>must</em>.' },
    { id: 'det15', time: 'now', clue: 'It’s Friday lunchtime. The noodle stall’s shutters are down, and a sign says “Closed until Monday”.',
      sentence: 'The noodle stall ___ be open.', answer: 'cant',
      why: 'The sign and the shutters rule it out: <em>can’t</em>.' },
    { id: 'det16', time: 'now', clue: 'Bow isn’t in class. She was coughing yesterday, but she also mentioned a dentist appointment “some time this week”.',
      sentence: 'She ___ be ill.', answer: 'might',
      why: 'The cough points to illness, the dentist points elsewhere: <em>might</em>.' },
    { id: 'det17', time: 'now', clue: 'Your brother has his headphones on and his eyes shut, and he’s drumming on the table and nodding his head.',
      sentence: 'He ___ be listening to music.', answer: 'must',
      why: 'Headphones, drumming and nodding: <em>must</em>, with <em>be listening</em> for an action going on now.' },
    { id: 'det18', time: 'now', clue: 'Kanya says she’s at tutoring, but her tutor has just messaged the group: “No class today. I’m ill.”',
      sentence: 'She ___ be at tutoring.', answer: 'cant',
      why: 'There is no class today, so tutoring is ruled out: <em>can’t</em>.' },
    { id: 'det19', time: 'now', clue: 'There’s a Thai milk tea with a heart drawn on the cup on your desk. Your best friend sometimes does this, and so does your deskmate.',
      sentence: 'It ___ be from your best friend.', answer: 'might',
      why: 'Two people could have left it: <em>might</em>.' },
    { id: 'det20', time: 'now', clue: 'A boy on the BTS platform is smiling and waving in your direction, but there’s a big group of students standing right behind you.',
      sentence: 'He ___ be waving at you.', answer: 'might',
      why: 'He could be waving at you or at the group behind you: <em>might</em>.' },

    /* ---- past ---- */
    { id: 'det21', time: 'past', clue: 'Nan’s umbrella is dripping and her shoes are soaking wet.',
      sentence: 'It ___ rained on her way here.', answer: 'must',
      why: 'A dripping umbrella and soaking shoes point to one cause: <em>must have</em> rained.' },
    { id: 'det22', time: 'past', clue: 'Ice says she walked to school in the heavy rain, but her hair, uniform and shoes are completely dry, and she has no umbrella.',
      sentence: 'She ___ walked here in the rain.', answer: 'cant',
      why: 'Bone dry with no umbrella? The rainy walk is ruled out: <em>can’t have</em>.' },
    { id: 'det23', time: 'past', clue: 'Your pencil case has gone. You had it in the library this morning, but you also took it to the canteen at lunch.',
      sentence: 'You ___ left it in the library.', answer: 'might',
      why: 'It could be in the library or the canteen: <em>might have</em>.' },
    { id: 'det24', time: 'past', clue: 'Your bubble tea was full when you went to the toilet. Now the cup is empty, and the straw has your sister’s pink lip gloss on it.',
      sentence: 'Your sister ___ drunk your bubble tea.', answer: 'must',
      why: 'Her lip gloss is on the straw: <em>must have</em> drunk it.' },
    { id: 'det25', time: 'past', clue: 'Your little brother says he ate the giant pizza all by himself, but there are still seven slices in the box.',
      sentence: 'He ___ eaten the whole thing.', answer: 'cant',
      why: 'Seven slices are still there, so the whole pizza is ruled out: <em>can’t have</em>.' },
    { id: 'det26', time: 'past', clue: 'Ning didn’t come to the BTS station at 8 as planned. She’s often late, but she also forgot a plan last week.',
      sentence: 'She ___ forgotten about it.', answer: 'might',
      why: 'She could be late or she could have forgotten: <em>might have</em>.' },
    { id: 'det27', time: 'past', clue: 'Toey got 50 out of 50 in the vocab test, and her flashcards are covered in notes and coffee stains.',
      sentence: 'She ___ studied really hard.', answer: 'must',
      why: 'A perfect score and well-used flashcards: <em>must have</em> studied.' },
    { id: 'det28', time: 'past', clue: 'Praew got 2 out of 50 in the test, and her vocabulary book still has the plastic wrapper on it.',
      sentence: 'She ___ studied very much.', answer: 'cant',
      why: 'An unopened book and 2/50 rule out serious study: <em>can’t have</em>.' },
    { id: 'det29', time: 'past', clue: 'You left your phone at home all day. Now the battery is on 3%, and Screen Time shows four hours of TikTok.',
      sentence: 'Someone ___ used it while you were out.', answer: 'must',
      why: 'You weren’t there, but somebody watched four hours: <em>must have</em>.' },
    { id: 'det30', time: 'past', clue: 'The cash machine at 7-Eleven kept Joy’s card. She isn’t sure of her new PIN, but the machine has broken down twice this week.',
      sentence: 'She ___ typed the wrong PIN.', answer: 'might',
      why: 'A wrong PIN or a broken machine: two explanations, so <em>might have</em>.' },
    { id: 'det31', time: 'past', clue: 'Nam says she saw the new Marvel film at the cinema last night, but it doesn’t come out in Thailand until next month.',
      sentence: 'She ___ seen it at the cinema last night.', answer: 'cant',
      why: 'The film isn’t showing here yet, so that is ruled out: <em>can’t have</em>.' },
    { id: 'det32', time: 'past', clue: 'This morning there was a whole box of mango sticky rice in the fridge. Now there’s an empty box, a spoon and a sticky trail to Dad’s room.',
      sentence: 'Dad ___ eaten it.', answer: 'must',
      why: 'The trail leads straight to Dad: <em>must have</em>.' },
    { id: 'det33', time: 'past', clue: 'Your friend’s birthday post got 300 likes, but none from Jeab. Jeab often misses posts, but the two of them argued last week.',
      sentence: 'Jeab ___ ignored it on purpose.', answer: 'might',
      why: 'Missing posts is normal for Jeab, but the argument is a reason too: <em>might have</em>.' },
    { id: 'det34', time: 'past', clue: 'The teacher thinks Mook copied Lin’s essay, but Mook handed hers in two days before Lin even started writing.',
      sentence: 'Mook ___ copied Lin’s essay.', answer: 'cant',
      why: 'You can’t copy an essay that doesn’t exist yet: <em>can’t have</em>.' },
    { id: 'det35', time: 'past', clue: 'After the class trip to Hua Hin, Gift’s face is bright red and her shoulders are peeling.',
      sentence: 'She ___ spent hours in the sun.', answer: 'must',
      why: 'Sunburn this bad leaves one explanation: <em>must have</em>.' },
    { id: 'det36', time: 'past', clue: 'Fon missed the school trip bus. She has overslept before, but the BTS also broke down this morning.',
      sentence: 'She ___ overslept again.', answer: 'might',
      why: 'Oversleeping or the BTS: both fit, so <em>might have</em>.' },
    { id: 'det37', time: 'past', clue: 'Your cousin says he walked from Siam to Don Mueang Airport in one hour. It’s about 25 kilometres.',
      sentence: 'He ___ walked all that way in an hour.', answer: 'cant',
      why: '25 km on foot in an hour is impossible: <em>can’t have</em>.' },
    { id: 'det38', time: 'past', clue: 'The classroom smells of durian, and there’s a spiky green shell in the bin under the teacher’s desk.',
      sentence: 'Someone ___ eaten durian in here.', answer: 'must',
      why: 'The smell and the shell point one way: <em>must have</em>.' },
    { id: 'det39', time: 'past', clue: 'Pang says she left her phone on the bus, but you just heard it ringing inside her school bag.',
      sentence: 'She ___ left it on the bus.', answer: 'cant',
      why: 'The phone is ringing in her bag, so the bus is ruled out: <em>can’t have</em>.' },
    { id: 'det40', time: 'past', clue: 'Kwan’s dog is shaking under the bed. There was a thunderstorm last night, but he also hates the vacuum cleaner, which Mum used an hour ago.',
      sentence: 'The storm ___ frightened him.', answer: 'might',
      why: 'The storm or the vacuum cleaner: two causes, so <em>might have</em>.' }
  ],

  /* ----------------------------------------------------------- CLIFF */
  cliff: [
    /* ---- present ---- */
    { id: 'cl1', text: 'It’s non-uniform day on Friday, so you ___ wear your uniform.', free: 'don’t have to', ban: 'mustn’t', answer: 'free',
      why: 'Non-uniform day makes uniform optional, not forbidden.' },
    { id: 'cl2', text: 'This is an exam. You ___ talk to the person next to you.', free: 'don’t have to', ban: 'mustn’t', answer: 'ban',
      why: 'Talking in an exam is against the rules: <em>mustn’t</em>.' },
    { id: 'cl3', text: 'The museum is free for students, so you ___ pay. Just show your student card.', free: 'don’t need to', ban: 'can’t', answer: 'free',
      why: 'It’s free, so paying isn’t necessary: <em>don’t need to</em>.' },
    { id: 'cl4', text: 'Sorry, this shop is cash only. You ___ pay by card.', free: 'don’t need to', ban: 'can’t', answer: 'ban',
      why: 'Cash only means cards are not accepted: <em>can’t</em>.' },
    { id: 'cl5', text: 'The school is providing lunch on the trip, so you ___ bring any food.', free: 'needn’t', ban: 'mustn’t', answer: 'free',
      why: 'Lunch is provided, so bringing food isn’t necessary: <em>needn’t</em>.' },
    { id: 'cl6', text: 'Passengers ___ eat or drink on the MRT. There’s a fine if you do.', free: 'needn’t', ban: 'mustn’t', answer: 'ban',
      why: 'A fine means a rule: <em>mustn’t</em>.' },
    { id: 'cl7', text: 'Students ___ use their phones during lessons. The teacher will take them away.', free: 'don’t have to', ban: 'aren’t allowed to', answer: 'ban',
      why: 'Phones get taken away, so using them is against the rules.' },
    { id: 'cl8', text: 'Students ___ buy the workbook. The teacher will send everyone a free PDF.', free: 'don’t have to', ban: 'aren’t allowed to', answer: 'free',
      why: 'A free PDF makes buying the book unnecessary, not forbidden.' },
    { id: 'cl9', text: 'The noodle shop always has lots of empty tables on Mondays, so we ___ book.', free: 'don’t need to', ban: 'can’t', answer: 'free',
      why: 'Empty tables make booking unnecessary; they are no reason to forbid it.' },
    { id: 'cl10', text: 'Children under 120 cm ___ go on this ride. It’s too dangerous for them.', free: 'don’t have to', ban: 'aren’t allowed to', answer: 'ban',
      why: 'A safety rule keeps small children off the ride: <em>aren’t allowed to</em>.' },
    { id: 'cl11', text: 'Marks in this practice quiz don’t count, so you ___ revise for it.', free: 'needn’t', ban: 'mustn’t', answer: 'free',
      why: 'The marks don’t count, so revising is optional, not forbidden.' },
    { id: 'cl12', text: 'This is the library. You ___ eat in here. Food brings ants.', free: 'don’t need to', ban: 'can’t', answer: 'ban',
      why: 'Eating in the library is against the rules: <em>can’t</em>.' },
    { id: 'cl13', text: 'You spent over 500 baht, so you ___ pay for delivery. It’s free.', free: 'don’t have to', ban: 'mustn’t', answer: 'free',
      why: 'Delivery is free, so there’s no obligation to pay.' },
    { id: 'cl14', text: 'You ___ tell anyone your bank PIN, not even your best friend.', free: 'don’t have to', ban: 'mustn’t', answer: 'ban',
      why: 'Sharing your PIN is something you must never do: <em>mustn’t</em>.' },
    { id: 'cl15', text: 'We ___ take a taxi to Siam. The BTS goes right there.', free: 'don’t need to', ban: 'can’t', answer: 'free',
      why: 'The BTS is an easy option, so a taxi isn’t necessary.' },
    { id: 'cl16', text: 'Visitors ___ take photos inside the temple hall. There are “No photos” signs everywhere.', free: 'don’t have to', ban: 'aren’t allowed to', answer: 'ban',
      why: 'The signs make it a rule: photos are forbidden.' },
    { id: 'cl17', text: 'You ___ print your ticket. The QR code on your phone is fine.', free: 'needn’t', ban: 'mustn’t', answer: 'free',
      why: 'The phone ticket works, so printing isn’t necessary: <em>needn’t</em>.' },
    { id: 'cl18', text: 'Customers ___ bring their own food into the cinema. Staff check every bag at the door.', free: 'don’t have to', ban: 'aren’t allowed to', answer: 'ban',
      why: 'Bag checks show outside food is against the rules.' },
    { id: 'cl19', text: 'The Saturday class is extra practice for anyone who wants it. You ___ come.', free: 'don’t have to', ban: 'mustn’t', answer: 'free',
      why: 'It’s for anyone who wants it, so coming is your choice.' },
    { id: 'cl20', text: 'You ___ cross the road here. There’s no crossing, and the cars come very fast.', free: 'don’t have to', ban: 'mustn’t', answer: 'ban',
      why: 'It’s dangerous, so the speaker is telling you not to: <em>mustn’t</em>.' },
    { id: 'cl21', text: 'Members ___ show their card at the gym. The camera at the door scans their face.', free: 'don’t need to', ban: 'can’t', answer: 'free',
      why: 'The face scan does the job, so the card isn’t necessary.' },
    { id: 'cl22', text: 'Dogs ___ come into the café. Only guide dogs are welcome.', free: 'don’t need to', ban: 'can’t', answer: 'ban',
      why: 'Only guide dogs are welcome, so other dogs are not allowed: <em>can’t</em>.' },
    { id: 'cl23', text: 'At my cousin’s school, students ___ wear a uniform. They can wear whatever they like.', free: 'don’t have to', ban: 'aren’t allowed to', answer: 'free',
      why: '“Whatever they like” means uniform is a choice: <em>don’t have to</em>.' },
    { id: 'cl24', text: 'At my school, students ___ dye their hair. It’s in the school rules.', free: 'don’t have to', ban: 'aren’t allowed to', answer: 'ban',
      why: 'A school rule forbids it: <em>aren’t allowed to</em>.' },
    { id: 'cl25', text: 'Bring your passport. You ___ open a bank account without it.', free: 'don’t need to', ban: 'can’t', answer: 'ban',
      why: 'Without a passport the bank says no: <em>can’t</em>.' },

    /* ---- past ---- */
    { id: 'cl26', text: 'I emailed my homework to the teacher a second time, but the first email had arrived safely. I ___ it again.', free: 'needn’t have sent', ban: 'wasn’t allowed to send', answer: 'free',
      why: 'She did send it again, and it wasn’t necessary: <em>needn’t have sent</em>.' },
    { id: 'cl27', text: 'On the school trip we ___ pay for the boat. It was included in the price.', free: 'didn’t have to', ban: 'weren’t allowed to', answer: 'free',
      why: 'The boat was already paid for, so paying wasn’t necessary.' },
    { id: 'cl28', text: 'When I was in primary school, I ___ walk home on my own. My mum said I was too young.', free: 'didn’t have to', ban: 'wasn’t allowed to', answer: 'ban',
      why: 'Mum said no, so it was forbidden: <em>wasn’t allowed to</em>.' },
    { id: 'cl29', text: 'We had plenty of time before the film, so we ___ take a taxi. We enjoyed the walk.', free: 'didn’t need to', ban: 'couldn’t', answer: 'free',
      why: 'Plenty of time made a taxi unnecessary: <em>didn’t need to</em>.' },
    { id: 'cl30', text: 'The palace had a strict dress code, so Nan ___ go in wearing shorts.', free: 'didn’t need to', ban: 'couldn’t', answer: 'ban',
      why: 'The dress code banned shorts: <em>couldn’t</em> = wasn’t allowed to.' },
    { id: 'cl31', text: 'I took a big umbrella to school, but it didn’t rain at all. I ___ it.', free: 'needn’t have taken', ban: 'wasn’t allowed to take', answer: 'free',
      why: 'She took it, and it wasn’t necessary: <em>needn’t have taken</em>.' },
    { id: 'cl32', text: 'At my old school, we ___ use our phones at break. Teachers kept them in a box until 4 p.m.', free: 'didn’t have to', ban: 'weren’t allowed to', answer: 'ban',
      why: 'Phones were locked away, so using them was forbidden.' },
    { id: 'cl33', text: 'When my mum was at our school, students ___ buy textbooks. The school lent them out for free.', free: 'didn’t have to', ban: 'weren’t allowed to', answer: 'free',
      why: 'Free loans made buying unnecessary, not forbidden.' },
    { id: 'cl34', text: 'Security at the concert was very strict, so we ___ take any water inside.', free: 'didn’t need to', ban: 'couldn’t', answer: 'ban',
      why: 'Strict security means a rule against it: <em>couldn’t</em>.' },
    { id: 'cl35', text: 'Mai queued for two hours for tickets, but then the band added a second show with plenty of seats. She ___ so long.', free: 'needn’t have queued', ban: 'wasn’t allowed to queue', answer: 'free',
      why: 'She did queue, and it turned out unnecessary: <em>needn’t have queued</em>.' },
    { id: 'cl36', text: 'Ploy ___ photos inside the museum, so she bought some postcards instead.', free: 'needn’t have taken', ban: 'wasn’t allowed to take', answer: 'ban',
      why: 'She bought postcards <em>instead</em>, so photos were forbidden.' },
    { id: 'cl37', text: 'The hotel gave us free towels, so we ___ bring our own.', free: 'didn’t need to', ban: 'couldn’t', answer: 'free',
      why: 'Free towels made our own unnecessary: <em>didn’t need to</em>.' },
    { id: 'cl38', text: 'During the exam we ___ leave the room, not even to go to the toilet.', free: 'didn’t have to', ban: 'weren’t allowed to', answer: 'ban',
      why: '“Not even to go to the toilet” describes a strict rule: forbidden.' },
    { id: 'cl39', text: 'Dad drove me to tutoring, but the class had been cancelled. He ___ me.', free: 'needn’t have driven', ban: 'wasn’t allowed to drive', answer: 'free',
      why: 'He did drive her, but there was no class: <em>needn’t have driven</em>.' },
    { id: 'cl40', text: 'When my dad was at boarding school, he ___ have a mobile phone. They were banned.', free: 'didn’t have to', ban: 'wasn’t allowed to', answer: 'ban',
      why: 'Phones were banned: <em>wasn’t allowed to</em>.' }
  ],

  /* ---------------------------------------------------- TIME MACHINE */
  timeMachine: [
    /* must (obligation) → had to */
    { id: 'tm1', now: 'Students must wear a tie on Mondays.',
      options: ['Last year students had to wear a tie on Mondays.',
                'Last year students must wore a tie on Mondays.',
                'Last year students must have worn a tie on Mondays.'], answer: 0,
      why: '<em>Must</em> has no past form for obligation: use <em>had to</em>. <em>Must have worn</em> would be a guess about the past.' },
    { id: 'tm2', now: 'I must finish my project tonight.',
      options: ['Last night I must finish my project.',
                'Last night I must had finished my project.',
                'Last night I had to finish my project.'], answer: 2,
      why: 'A time word can’t make <em>must</em> past. The past of obligation is <em>had to</em>; <em>must had</em> is never correct.' },
    { id: 'tm3', now: 'You must check in two hours before an international flight.',
      options: ['Last month we must check in two hours before our flight to Tokyo.',
                'Last month we had to check in two hours before our flight to Tokyo.',
                'Last month we must have checked in two hours before our flight to Tokyo.'], answer: 1,
      why: 'Past obligation = <em>had to</em>. <em>Must have checked in</em> is a guess, not a rule we followed.' },

    /* have to → had to */
    { id: 'tm4', now: 'I have to take two buses to get to school.',
      options: ['When I lived in Nonthaburi, I had to take two buses to get to school.',
                'When I lived in Nonthaburi, I have had to take two buses to get to school.',
                'When I lived in Nonthaburi, I must take two buses to get to school.'], answer: 0,
      why: 'A finished time (<em>when I lived …</em>) needs the past simple: <em>had to</em>. The present perfect can’t go with a finished time.' },
    { id: 'tm5', now: 'Do you have to pay for the lockers?',
      options: ['Had you to pay for the lockers yesterday?',
                'Did you had to pay for the lockers yesterday?',
                'Did you have to pay for the lockers yesterday?'], answer: 2,
      why: '<em>Have to</em> makes past questions with <em>did</em> + base form: <em>Did you have to …?</em> Not <em>Had you to</em> (old-fashioned) or <em>did … had</em>.' },

    /* mustn't → wasn't allowed to / couldn't */
    { id: 'tm6', now: 'We mustn’t use our phones during the exam.',
      options: ['In last week’s exam we weren’t allowed to use our phones.',
                'In last week’s exam we mustn’t use our phones.',
                'In last week’s exam we mustn’t have used our phones.'], answer: 0,
      why: '<em>Mustn’t</em> has no past. For a past ban use <em>wasn’t / weren’t allowed to</em> or <em>couldn’t</em>.' },
    { id: 'tm7', now: 'Visitors mustn’t take photos inside the temple.',
      options: ['On our trip last month, we didn’t have to take photos inside the temple.',
                'On our trip last month, we couldn’t take photos inside the temple.',
                'On our trip last month, we mustn’t took photos inside the temple.'], answer: 1,
      why: 'A past ban: <em>couldn’t</em>. <em>Didn’t have to</em> means “not necessary”, which changes the meaning.' },
    { id: 'tm8', now: 'My little sister mustn’t go out alone after dark.',
      options: ['When I was her age, I hadn’t to go out alone after dark.',
                'When I was her age, I wasn’t allowed to go out alone after dark.',
                'When I was her age, I didn’t allowed to go out alone after dark.'], answer: 1,
      why: 'Past ban = <em>wasn’t allowed to</em>, with <em>be</em>, not <em>do</em>. <em>Hadn’t to</em> is not modern English.' },

    /* don't have to → didn't have to */
    { id: 'tm9', now: 'We don’t have to wear uniform on Sports Day.',
      options: ['Last Sports Day we hadn’t to wear uniform.',
                'Last Sports Day we didn’t have to wear uniform.',
                'Last Sports Day we mustn’t wear uniform.'], answer: 1,
      why: 'No obligation in the past = <em>didn’t have to</em>. <em>Mustn’t</em> would make uniform forbidden.' },
    { id: 'tm10', now: 'You don’t have to pay for the museum on Sundays.',
      options: ['Last Sunday we didn’t have to pay for the museum.',
                'Last Sunday we weren’t allowed to pay for the museum.',
                'Last Sunday we didn’t had to pay for the museum.'], answer: 0,
      why: '<em>Didn’t</em> + base form: <em>didn’t have to</em>. <em>Weren’t allowed to</em> means it was forbidden.' },

    /* needn't → didn't need to / needn't have */
    { id: 'tm11', now: 'We needn’t book a table. The restaurant is never busy on Mondays.',
      options: ['Last Monday we didn’t need to book a table, so we just walked in.',
                'Last Monday we needn’t book a table, so we just walked in.',
                'Last Monday we needn’t have booked a table, so we just walked in.'], answer: 0,
      why: 'We didn’t book, so <em>didn’t need to</em>. <em>Needn’t have booked</em> would mean we <strong>did</strong> book.' },
    { id: 'tm12', now: 'You needn’t bring a calculator to the test.',
      options: ['For yesterday’s test we didn’t needed to bring a calculator.',
                'For yesterday’s test we needn’t bring a calculator.',
                'For yesterday’s test we didn’t need to bring a calculator.'], answer: 2,
      why: 'Plain <em>needn’t</em> can’t look back. For no need in the past (done or not), use <em>didn’t need to</em> + base form. <em>Didn’t needed</em> doubles the past.' },
    { id: 'tm13', now: 'Lek needn’t take a taxi. The station is only five minutes away. But she’s booking one anyway.',
      options: ['Yesterday Lek needn’t took a taxi. The station was only five minutes away.',
                'Yesterday Lek mustn’t have taken a taxi. The station was only five minutes away.',
                'Yesterday Lek needn’t have taken a taxi. The station was only five minutes away.'], answer: 2,
      why: 'She <strong>did</strong> take the taxi, and it wasn’t necessary: <em>needn’t have taken</em>. <em>Mustn’t</em> is about rules, not about what was unnecessary.' },
    { id: 'tm14', now: 'Mint needn’t run to the cinema. The film doesn’t start until 8. But she’s running anyway.',
      options: ['Last night Mint needn’t run to the cinema. The film didn’t start until 8.',
                'Last night Mint needn’t have run to the cinema. The film didn’t start until 8.',
                'Last night Mint hadn’t to run to the cinema. The film didn’t start until 8.'], answer: 1,
      why: 'She ran, but it wasn’t necessary: <em>needn’t have run</em>. Plain <em>needn’t run</em> can’t look back.' },

    /* must (deduction) → must have */
    { id: 'tm15', now: 'Fon isn’t answering her phone. She must be asleep.',
      options: ['Fon didn’t answer her phone last night. She must had been asleep.',
                'Fon didn’t answer her phone last night. She must have been asleep.',
                'Fon didn’t answer her phone last night. She must was asleep.'], answer: 1,
      why: 'A past guess = <em>must have</em> + past participle. A modal is never followed by <em>had</em> or <em>was</em>.' },
    { id: 'tm16', now: 'Everyone is coming in with wet umbrellas. It must be raining.',
      options: ['Everyone came in with wet umbrellas this morning. It must have been raining.',
                'Everyone came in with wet umbrellas this morning. It must rained.',
                'Everyone came in with wet umbrellas this morning. It must had rained.'], answer: 0,
      why: 'Past deduction: <em>must have been raining</em>. After a modal, the past goes into <em>have</em> + past participle.' },

    /* can't (deduction) → can't have */
    { id: 'tm17', now: 'Nam can’t be at home. Her shoes aren’t by the door.',
      options: ['Nam mustn’t have been at home last night. Her shoes weren’t by the door.',
                'Nam can’t be at home last night. Her shoes weren’t by the door.',
                'Nam can’t have been at home last night. Her shoes weren’t by the door.'], answer: 2,
      why: 'Sure it didn’t happen = <em>can’t have</em> + past participle. The opposite of <em>must have</em> is <em>can’t have</em>, never <em>mustn’t have</em>.' },
    { id: 'tm18', now: 'Sai can’t know about the party. Nobody told her.',
      options: ['Sai can’t have known about the party last week. Nobody told her.', 'Sai can’t knew about the party last week. Nobody told her.', 'Sai mustn’t have known about the party last week. Nobody told her.'], answer: 0,
      why: '<em>Can’t have known</em> = I’m sure she didn’t. A modal needs <em>have</em> before the past participle, and the opposite of <em>must have</em> is <em>can’t have</em>.' },
    { id: 'tm19', now: 'The test can’t be very difficult. Everyone is finishing early.',
      options: ['Yesterday’s test mustn’t have been very difficult. Everyone finished early.',
                'Yesterday’s test can’t have been very difficult. Everyone finished early.',
                'Yesterday’s test can’t had been very difficult. Everyone finished early.'], answer: 1,
      why: 'Past deduction, negative: <em>can’t have been</em>. <em>Mustn’t</em> is for rules; for a sure-not guess use <em>can’t have</em>.' },

    /* might → might have */
    { id: 'tm20', now: 'Bow isn’t here yet. She might be stuck in traffic.',
      options: ['Bow was late this morning. She might was stuck in traffic.',
                'Bow was late this morning. She might had been stuck in traffic.',
                'Bow was late this morning. She might have been stuck in traffic.'], answer: 2,
      why: 'A 50% guess about the past: <em>might have</em> + past participle.' },
    { id: 'tm21', now: 'Pang looks really happy. She might know her test results.',
      options: ['Pang looked really happy yesterday. She might knew her test results.',
                'Pang looked really happy yesterday. She might have known her test results.',
                'Pang looked really happy yesterday. She might have know her test results.'], answer: 1,
      why: '<em>Might have</em> + past participle (<em>known</em>), not the past simple or the base form.' },

    /* should (advice) → should have */
    { id: 'tm22', now: 'You should book the tickets early. They always sell out.',
      options: ['You should booked the tickets earlier. They sold out last week.',
                'You must have booked the tickets earlier. They sold out last week.',
                'You should have booked the tickets earlier. They sold out last week.'], answer: 2,
      why: 'Past advice that wasn’t followed = criticism: <em>should have booked</em>. <em>Must have booked</em> is a guess.' },
    { id: 'tm23', now: 'You should take an umbrella. It’s going to rain.',
      options: ['You should have taken an umbrella this morning. Look how wet you are!',
                'You should took an umbrella this morning. Look how wet you are!',
                'You should have took an umbrella this morning. Look how wet you are!'], answer: 0,
      why: '<em>Should have</em> + past participle: <em>taken</em>, not <em>took</em>.' },

    /* shouldn't → shouldn't have */
    { id: 'tm24', now: 'You shouldn’t eat so much durian before bed.',
      options: ['You shouldn’t ate so much durian last night. No wonder you feel sick.',
                'You shouldn’t have eaten so much durian last night. No wonder you feel sick.',
                'You didn’t should eat so much durian last night. No wonder you feel sick.'], answer: 1,
      why: 'You did it, and it was a mistake: <em>shouldn’t have eaten</em>. <em>Should</em> never takes <em>did</em>.' },
    { id: 'tm25', now: 'We shouldn’t stay up so late. We have an exam tomorrow.',
      options: ['We shouldn’t stayed up so late last night. I fell asleep in the exam!',
                'We mustn’t have stayed up so late last night. I fell asleep in the exam!',
                'We shouldn’t have stayed up so late last night. I fell asleep in the exam!'], answer: 2,
      why: 'Regret about the past: <em>shouldn’t have stayed</em>. <em>Mustn’t</em> is for rules, so it can’t express regret.' },

    /* can (ability) → could / was able to / managed to */
    { id: 'tm26', now: 'My little brother can swim really well.',
      options: ['When he was only five, my little brother could swim really well.',
                'When he was only five, my little brother can swim really well.',
                'When he was only five, my little brother could swam really well.'], answer: 0,
      why: 'General ability in the past: <em>could</em> + base form.' },
    { id: 'tm27', now: 'The test is hard, but I think I can finish it in time.',
      options: ['The test was hard, but I could finish it in time.',
                'The test was hard, but I can finished it in time.',
                'The test was hard, but I was able to finish it in time.'], answer: 2,
      why: 'One success on one occasion: <em>was able to</em>. Positive <em>could</em> is for general ability, not a single achievement.' },
    { id: 'tm28', now: 'The concert is sold out, but I hope we can get tickets from a friend.',
      options: ['The concert was sold out, but in the end we could get two tickets from a friend.',
                'The concert was sold out, but in the end we managed to get two tickets from a friend.',
                'The concert was sold out, but in the end we managed get two tickets from a friend.'], answer: 1,
      why: 'A single success after difficulty: <em>managed to</em> (with <em>to</em>). Positive <em>could</em> doesn’t work for one achievement.' },

    /* will (willingness) → would */
    { id: 'tm29', now: 'My little sister won’t eat vegetables.',
      options: ['When she was small, my little sister wouldn’t eat vegetables.',
                'When she was small, my little sister won’t eat vegetables.',
                'When she was small, my little sister wouldn’t ate vegetables.'], answer: 0,
      why: 'Past refusal: <em>wouldn’t</em> + base form. <em>Won’t</em> is the present.' },
    { id: 'tm30', now: 'My laptop won’t turn on!',
      options: ['Last night my laptop won’t turn on, so I couldn’t finish my essay.',
                'Last night my laptop wouldn’t turned on, so I couldn’t finish my essay.',
                'Last night my laptop wouldn’t turn on, so I couldn’t finish my essay.'], answer: 2,
      why: 'A machine “refusing” in the past: <em>wouldn’t turn on</em>, with the base form after the modal.' }
  ]
};

/* ---------------------------------------------------------------- CARDS
   [form, function label, CEFR, theme key, meaning, Thai meaning, example] */
var MODAL_CARD_THEMES = {
  certain:   'How sure? (now)',
  pastguess: 'How sure? (past)',
  oblig:     'Must & have to',
  noneed:    'No need vs not allowed',
  advice:    'Advice & regret',
  ability:   'Ability',
  polite:    'Requests, offers & permission',
  past:      'Past forms',
  hedge:     'Hedging & stance'
};

var MODAL_CARDS = [
  /* ---- certain ---- */
  ['must', 'deduction · about 90% sure', 'B1+', 'certain', 'I’m almost sure this is true, because of the evidence.', 'ต้อง…แน่ ๆ (มั่นใจราว 90% จากหลักฐาน)', 'Her eyes are red. She must be really tired.'],
  ['can’t', 'deduction · about 90% sure it’s not true', 'B1+', 'certain', 'I’m almost sure this is not true.', 'ไม่มีทางที่จะ… (มั่นใจราว 90% ว่าไม่จริง)', 'You’ve just eaten two plates of rice. You can’t be hungry again!'],
  ['may / might / could', 'possibility · about 50%', 'B1', 'certain', 'Perhaps this is true; maybe yes, maybe no.', 'อาจจะ… (ราว 50%)', 'Someone’s at the door. It might be the Grab driver.'],
  ['may not / might not (mightn’t)', 'possibility · maybe not', 'B1+', 'certain', 'Perhaps this is not true.', 'อาจจะไม่… (ราว 50%)', 'The shop might not be open yet. Let’s check online.'],
  ['couldn’t (guessing)', 'deduction · a strong no, like can’t', 'B2', 'certain', 'I’m almost sure this is not true. It is not a 50% guess.', 'ไม่มีทางที่จะ… (หนักแน่นเท่ากับ can’t)', 'That couldn’t be Ploy. She’s in Chiang Mai this week.'],
  ['will', 'confident guess from what you know', 'B2', 'certain', 'I’m confident because I know how things usually go. I don’t need to check.', 'คงจะ…แน่ ๆ (เพราะเป็นแบบนี้เป็นประจำ)', 'Someone’s knocking. That’ll be the delivery driver. He always comes at three.'],
  ['should / ought to', 'expectation from a plan or timetable', 'B2', 'certain', 'If everything goes to plan, this is what I expect.', 'น่าจะ… (ตามแผนหรือกำหนดการ)', 'She left an hour ago, so she should be home by now.'],
  ['must be + -ing', 'deduction about an action happening now', 'B2', 'certain', 'I’m almost sure this is happening right now.', 'ต้องกำลัง…อยู่แน่ ๆ', 'I can hear typing. She must be working on her essay.'],

  /* ---- pastguess ---- */
  ['must have + past participle', 'past deduction · about 90% sure', 'B2', 'pastguess', 'I’m almost sure this happened.', 'ต้อง…ไปแล้วแน่ ๆ (เรื่องในอดีต)', 'The ground is wet. It must have rained last night.'],
  ['can’t have + past participle', 'past deduction · about 90% sure it didn’t happen', 'B2', 'pastguess', 'I’m almost sure this did not happen.', 'ไม่มีทางที่จะ…ไปได้ (เรื่องในอดีต)', 'She can’t have seen the message. Her phone was off all day.'],
  ['couldn’t have + past participle', 'past deduction · about 90% sure it didn’t happen', 'C1', 'pastguess', 'Same as can’t have: I’m almost sure it didn’t happen.', 'ไม่มีทางที่จะ… (หนักแน่นเท่ากับ can’t have)', 'He couldn’t have eaten the whole pizza. There are seven slices left.'],
  ['may have / might have + past participle', 'past possibility · about 50%', 'B2', 'pastguess', 'Perhaps this happened, but I’m not sure.', 'อาจจะ…ไปแล้ว (ราว 50%)', 'I can’t find my keys. I might have left them at school.'],
  ['could have + past participle', 'past possibility · about 50%', 'B2', 'pastguess', 'This is one possible explanation of what happened.', 'อาจจะ…ไปแล้วก็ได้', 'Fon missed the bus. She could have overslept.'],
  ['may not have / might not have + past participle', 'past possibility · maybe not', 'B2', 'pastguess', 'Perhaps this did not happen.', 'อาจจะไม่ได้…', 'She may not have seen your message yet.'],
  ['must have been + -ing', 'past deduction about an ongoing action', 'B2+', 'pastguess', 'I’m almost sure this was going on at that time.', 'ตอนนั้นต้องกำลัง…อยู่แน่ ๆ', 'Her eyes were red. She must have been crying.'],
  ['will have + past participle', 'confident guess about the past', 'C1', 'pastguess', 'I’m sure this has happened by now. I don’t need to check.', 'ป่านนี้คง…แล้วแน่ ๆ', 'Don’t call Ploy now. She’ll have gone to bed. She’s always asleep by ten.'],

  /* ---- oblig ---- */
  ['have to', 'obligation · not my idea', 'B1', 'oblig', 'It is necessary, but it’s not my idea: I’m passing on a rule, or the situation makes it necessary.', 'ต้อง… (ไม่ใช่ความคิดของผู้พูด แต่เป็นกฎที่คนอื่นตั้งหรือสถานการณ์บังคับ)', 'I have to wear a uniform at my new job.'],
  ['must', 'obligation · the speaker says so', 'B1', 'oblig', 'It is necessary, and I say so: my own decision, a parent or teacher giving an order, or the school’s own notice.', 'ต้อง… (ผู้พูดเป็นคนกำหนดหรือเห็นด้วยเอง เช่น ตัดสินใจเอง ครู/พ่อแม่สั่ง หรือประกาศของโรงเรียน)', 'I must call Grandma tonight. It’s her birthday.'],
  ['need to', 'necessity', 'B1', 'oblig', 'It is necessary.', 'จำเป็นต้อง…', 'You need to bring your passport to open a bank account.'],
  ['Do I have to …?', 'asking about obligation', 'B1', 'oblig', 'Is it necessary? Questions with have to use do or does.', 'ต้อง…ไหม', 'Do we have to pay to go into the museum?'],
  ['have got to', 'obligation · informal speech', 'B1+', 'oblig', 'It is necessary; common in everyday spoken English.', 'ต้อง… (ภาษาพูด)', 'I’ve got to go. My mum is waiting outside.'],
  ['be supposed to', 'a rule, plan or expectation', 'B2', 'oblig', 'There is a rule, plan or expectation. We often use it when it isn’t followed.', 'ควรจะ…ตามกฎหรือตามที่ตกลงกันไว้ (แต่มักไม่ได้ทำ)', 'We’re supposed to be in class by 8, but Bow never is.'],
  ['be required to', 'formal obligation', 'B2+', 'oblig', 'It is necessary because of an official rule.', 'ถูกกำหนดให้ต้อง… (ภาษาทางการ)', 'All students are required to wear their ID card on campus.'],

  /* ---- noneed ---- */
  ['don’t have to', 'no obligation', 'B1', 'noneed', 'It isn’t necessary. You can choose.', 'ไม่จำเป็นต้อง… (จะทำหรือไม่ทำก็ได้)', 'You don’t have to pay. The museum is free on Sundays.'],
  ['don’t need to', 'no necessity', 'B1', 'noneed', 'It isn’t necessary.', 'ไม่จำเป็นต้อง…', 'We don’t need to change money. The hotel has a cash machine.'],
  ['needn’t', 'no necessity · no to after it', 'B1+', 'noneed', 'It isn’t necessary; the same as don’t need to.', 'ไม่ต้อง…ก็ได้', 'You needn’t print your ticket. The one on your phone is fine.'],
  ['mustn’t', 'prohibition', 'B1', 'noneed', 'Don’t do it: it is not allowed, or it is a very bad idea.', 'ห้าม… / ต้องไม่…', 'You mustn’t tell anyone your PIN, not even your best friend.'],
  ['can’t', 'refusing permission', 'B1', 'noneed', 'It is not allowed.', '…ไม่ได้ / ไม่อนุญาตให้…', 'Sorry, you can’t pay by card here. It’s cash only.'],
  ['isn’t / aren’t allowed to', 'prohibition · a rule', 'B1', 'noneed', 'A rule says no.', 'ไม่ได้รับอนุญาตให้…', 'Students aren’t allowed to use their phones in class.'],
  ['mustn’t vs don’t have to', 'the negatives that flip the meaning', 'B1+', 'noneed', 'Mustn’t means not allowed. Don’t have to means not necessary.', 'mustn’t = ห้าม ส่วน don’t have to = ไม่จำเป็นต้อง', 'You mustn’t be late, but you don’t have to wear uniform.'],
  ['be not to', 'formal instruction · prohibition', 'C1', 'noneed', 'An official order not to do something.', 'ห้าม… (คำสั่งแบบทางการ)', 'Students are not to leave the exam room before 10 a.m.'],

  /* ---- advice ---- */
  ['should', 'advice', 'B1', 'advice', 'It’s a good idea.', 'ควร…', 'You should try the mango sticky rice. It’s delicious.'],
  ['shouldn’t', 'advice · negative', 'B1', 'advice', 'It’s not a good idea.', 'ไม่ควร…', 'You shouldn’t spend all your pocket money on the first day.'],
  ['ought to', 'advice · keeps its to', 'B1+', 'advice', 'It’s a good idea; like should, but less common.', 'ควร… (ความหมายเหมือน should)', 'You ought to ask the driver before you get on.'],
  ['You’d better … (had better)', 'strong advice · a warning', 'B1+', 'advice', 'Do it now, or there could be a problem.', '…ดีกว่านะ ไม่อย่างนั้นอาจมีปัญหา', 'You’d better hurry, or you’ll miss the last train.'],
  ['had better not', 'warning · negative', 'B1+', 'advice', 'Don’t do it, or there could be a problem.', 'อย่า…จะดีกว่า', 'You’d better not be late again. The teacher is already annoyed.'],
  ['should have / ought to have + past participle', 'past · criticism or regret', 'B2', 'advice', 'It was a good idea, but it didn’t happen.', 'ควรจะ… (แต่ตอนนั้นไม่ได้ทำ)', 'I should have taken an umbrella. I’m soaking wet.'],
  ['shouldn’t have + past participle', 'past · regret about something done', 'B2', 'advice', 'You did it, and it was a mistake.', 'ไม่น่า…เลย', 'I shouldn’t have eaten so much durian last night.'],
  ['Why don’t you …?', 'suggestion', 'B1', 'advice', 'A friendly way to suggest an idea.', 'ทำไมไม่ลอง…ดูล่ะ', 'Why don’t you ask the teacher for more time?'],
  ['If I were you, I’d …', 'advice', 'B1+', 'advice', 'This is what I would do in your situation.', 'ถ้าฉันเป็นเธอ ฉันจะ…', 'If I were you, I’d say sorry to her today.'],

  /* ---- ability ---- */
  ['can', 'ability · now', 'B1', 'ability', 'You know how to do it, or it is possible.', '…ได้ / …เป็น', 'My sister can speak three languages.'],
  ['can’t', 'no ability · now', 'B1', 'ability', 'You don’t know how, or it isn’t possible.', '…ไม่ได้ / …ไม่เป็น', 'I can’t swim, so I stay in the shallow end.'],
  ['could', 'general ability in the past', 'B1', 'ability', 'You knew how to do it at that time.', '…ได้ (ความสามารถทั่วไปในอดีต)', 'When I was six, I could already read Thai and English.'],
  ['couldn’t', 'no ability in the past', 'B1', 'ability', 'You didn’t know how, or it wasn’t possible.', '…ไม่ได้ (ในอดีต)', 'I couldn’t open the jar. The lid was too tight.'],
  ['was / were able to', 'one success in the past', 'B1+', 'ability', 'You succeeded on one particular occasion.', 'ทำ…ได้ (สำเร็จในครั้งนั้น)', 'The test was hard, but I was able to finish it in time.'],
  ['managed to', 'one success after difficulty', 'B1+', 'ability', 'You succeeded, although it was difficult.', 'ทำ…ได้สำเร็จ (แม้จะยาก)', 'The concert was sold out, but we managed to get two tickets.'],
  ['could have + past participle', 'a past chance not taken', 'B2', 'ability', 'It was possible, but you didn’t do it.', '…ก็ได้นี่ (แต่ตอนนั้นไม่ได้ทำ)', 'You could have asked me for help. Why didn’t you?'],

  /* ---- polite ---- */
  ['Can I …? / Could I …?', 'asking for permission', 'B1', 'polite', 'Asking if you may do something; could is more polite.', 'ขอ…ได้ไหม', 'Could I borrow your charger for a minute?'],
  ['May I …?', 'asking for permission · formal', 'B1+', 'polite', 'A very polite, formal way to ask for permission.', 'ขออนุญาต…ได้ไหม', 'May I leave the room, please?'],
  ['Could you …?', 'polite request', 'B1', 'polite', 'Asking someone politely to do something.', 'ช่วย…หน่อยได้ไหม', 'Could you send me the homework on LINE?'],
  ['Would you mind + -ing?', 'polite request', 'B1+', 'polite', 'A polite way to ask someone to do something.', 'รบกวนช่วย…ได้ไหม', 'Would you mind closing the window?'],
  ['Would you mind if I + past simple?', 'asking for permission · very polite', 'B2', 'polite', 'A very polite way to ask if you can do something.', 'จะเป็นอะไรไหมถ้าฉันจะ…', 'Would you mind if I opened the window?'],
  ['Do you mind if I + present simple?', 'asking for permission · polite', 'B1+', 'polite', 'A polite way to ask if you can do something.', 'ถ้าฉันจะ… จะว่าอะไรไหม', 'Do you mind if I sit here?'],
  ['Shall I …?', 'offer', 'B1', 'polite', 'Offering to do something for someone.', 'ให้ฉัน…ไหม', 'It’s hot in here. Shall I turn on the air conditioner?'],
  ['Would you like me to …?', 'offer · polite', 'B1+', 'polite', 'A polite way to offer help.', 'อยากให้ฉันช่วย…ไหม', 'Would you like me to carry your bag?'],
  ['be allowed to', 'permission · a rule says yes', 'B1', 'polite', 'A rule or a person gives you permission.', 'ได้รับอนุญาตให้…', 'We’re allowed to use our phones at lunchtime.'],

  /* ---- past ---- */
  ['had to', 'past obligation', 'B1', 'past', 'It was necessary, and you did it.', 'ต้อง… (ในอดีต และได้ทำจริง)', 'The card machine was broken, so we had to pay in cash.'],
  ['didn’t have to', 'past · no obligation', 'B1+', 'past', 'It wasn’t necessary.', 'ไม่จำเป็นต้อง… (ในอดีต)', 'We didn’t have to pay for the museum. It was free for students.'],
  ['needed to', 'past necessity', 'B1+', 'past', 'It was necessary.', 'จำเป็นต้อง… (ในอดีต)', 'We needed to change some money at the airport.'],
  ['didn’t need to', 'past · no necessity', 'B2', 'past', 'It wasn’t necessary. It doesn’t say if you did it.', 'ไม่จำเป็นต้อง… (ในอดีต ไม่ได้บอกว่าทำหรือไม่)', 'We didn’t need to book. The restaurant was almost empty.'],
  ['needn’t have + past participle', 'past · no necessity', 'B2', 'past', 'You did it, but it wasn’t necessary.', 'ทำไปแล้ว แต่จริง ๆ ไม่จำเป็นต้องทำ', 'You needn’t have bought me a present — but thank you!'],
  ['wasn’t / weren’t allowed to', 'past prohibition', 'B1+', 'past', 'A rule said no in the past.', 'ไม่ได้รับอนุญาตให้… (ในอดีต)', 'We weren’t allowed to take photos inside the palace.'],
  ['couldn’t', 'past · not allowed or not possible', 'B1+', 'past', 'It wasn’t allowed, or it wasn’t possible.', '…ไม่ได้ (ในอดีต เพราะไม่ได้รับอนุญาตหรือทำไม่ได้)', 'When I was small, I couldn’t go to the shops on my own.'],
  ['Did you have to …?', 'past question about obligation', 'B1+', 'past', 'Was it necessary? Past questions with have to use did.', 'ตอนนั้นต้อง…ไหม', 'Did you have to show your ID when you bought the phone?'],
  ['wouldn’t', 'past refusal', 'B2', 'past', 'Someone or something refused to do it.', 'ไม่ยอม… (ในอดีต)', 'My laptop wouldn’t turn on, so I couldn’t finish my essay.'],

  /* ---- hedge ---- */
  ['may well', 'strong possibility', 'C1', 'hedge', 'This is quite likely to be true.', 'มีความเป็นไปได้สูงว่า…', 'Online learning may well replace some classroom teaching.'],
  ['could well', 'real possibility', 'C1', 'hedge', 'This is a real possibility.', 'อาจจะ…ได้จริง ๆ', 'Without action, the problem could well get worse.'],
  ['is likely to', 'probability', 'B2', 'hedge', 'This will probably happen or be true.', 'มีแนวโน้มที่จะ…', 'Prices are likely to rise again next year.'],
  ['is unlikely to', 'low probability', 'B2', 'hedge', 'This probably won’t happen.', 'ไม่น่าจะ…', 'The new rule is unlikely to solve the problem on its own.'],
  ['it could be argued that', 'presenting a view carefully', 'C1', 'hedge', 'A careful way to give a view others may not share.', 'อาจกล่าวได้ว่า…', 'It could be argued that social media does more harm than good.'],
  ['would appear to', 'cautious claim from evidence', 'C1', 'hedge', 'The evidence suggests this, but I’m being careful.', 'ดูเหมือนว่าจะ…', 'The results would appear to support the theory.'],
  ['may / might (in essays)', 'softening a claim', 'B2', 'hedge', 'Makes a claim less strong, so it is easier to defend.', 'อาจ… (ช่วยให้ข้อความไม่ฟันธงเกินไป)', 'Longer school days may lead to more stress for students.'],
  ['it is possible that', 'tentative possibility', 'B2', 'hedge', 'This may be true, but we can’t be sure.', 'เป็นไปได้ว่า…', 'It is possible that the data is incomplete.']
];
